### PR TITLE
Enable gzip encoding if server supports it

### PR DESCRIPTION
**Pull request by lstrojny**
This patch enables gzip encoding if the solr server supports it.

### CODE REVIEW

**Comment by 0mars** [comment]
@lstrojny can you fix the failing tests
```
TEST 21/145 [tests/013.solrclient_getByIds.phpt]

========DIFF========

007+ Accept-Encoding: deflate, gzip
```
```
TEST 30/145 [tests/019.solrclient_getdebug.phpt]

========DIFF========

002+ Accept-Encoding: deflate, gzip
```

**Comment by lstrojny** [comment]
@0mars done

**Comment by 0mars** [comment]
Looks good, can you create a ticket at bugs,php.net as a New Feature, so that we include it in the commit, Thanks

**Comment by lstrojny** [comment]
Here we go: https://bugs.php.net/bug.php?id=73031

**Comment by php-pulls** [comment]
**Comment on behalf of omars at php.net:**

merged, Thanks!

**Pull request closed without merging**
